### ISSUE TITLE
Admin codes

### ISSUE THREAD

**Issue by falaileh** [ArielSaldana/palringo-python-bot#1]
im not good in python , and i downloaded ur python palringo bot project , i just wanna ask you how to kick and ban cmd will work  ? 

i wish if u help me with that :)  thank you

**Comment by ArielSaldana** [comment]
Hey Falaileh,

if you look at PacketTemplate.py you'll see all the packets defined. 

Here's an example of how to use the ban command.

`sock.sendall(packets.banUser(groupId, userId))`
